### ISSUE TITLE
Write CompanyDirectory project description

### ISSUE THREAD

**Issue by nikosportolos** [Nickmeister/MindTheCode#80]
Draft:

> Restful API με βασικό στόχο την διαχείριση του οργανογράμματος ενός οργανισμού, την επεξεργασία των βασικών στοιχείων των εργαζόμενων και παράλληλα να αποτελέσει την βασική πηγή άντλησης πληροφοριών από όλες τις εφαρμογές της εταιρείας.

**Comment by dimitrafountzoula** [comment]
Draft2:
Restful API για τη διαχείριση της οργανωτικής δομής ενός οργανισμού. Στόχος είναι η επεξεργασία των βασικών στοιχείων των εργαζόμενων καθώς επίσης και η δυνατότητα να αποτελέσει την βασική πηγή άντλησης πληροφοριών από όλες τις εφαρμογές της εταιρείας.
