### ISSUE TITLE
Write Timesheet project description

### ISSUE THREAD

**Issue by nikosportolos** [Nickmeister/MindTheCode#81]
Draft:

> Web-based εφαρμογή για την καταχώρηση του χρόνου που αφιερώθηκε και πρέπει να αποζημιωθεί στο πλαίσιο υλοποίησης των έργων.

**Comment by dimitrafountzoula** [comment]
Draft2:
Web-based εφαρμογή για την καταχώρηση του χρόνου που αφιέρωσε ο χρήστης κατά τη διάρκεια υλοποίησης ενός έργου και εμφάνιση του συνολικού κόστους για κάθε έργο.
